repos:
- repo: local
  hooks:
  - id: tartufo
    name: Tartufo
    entry: tartufo
    args: [--pre_commit, --cleanup]
    language: python
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.730
  hooks:
  - id: mypy
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.4.2
  hooks:
  - id: pylint
