repos:
- repo: local
  hooks:
  - id: tartufo
    name: tartufo
    entry: tartufo
    args: [--pre_commit, --cleanup]
    language: python
    pass_filenames: false
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.730
  hooks:
  - id: mypy
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
