dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: test
      script: ./scripts/lint_and_test.sh
    - stage: lint_and_test
      # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master
      script: ./scripts/build_and_deploy_wheel.sh
#deploy:
#  provider: pypi
#  user: $PYPI_USER
#  password:
#    secure: $PYPI_PASS
#  on:
#    branch: master
