language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
install: pip install tox-travis codecov
script: tox
after_success: codecov
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  - provider: pypi
    user: "__token__"
    password: $PYPI_DEPLOY_KEY
    on:
      tags: true
      python: 3.7
      condition: $TOXENV = py37
      distributions: sdist bdist_wheel
      repo: godaddy/tartufo
  # FIXME: Uncomment once deployment user is determined.
  # - provider: script
  #   script: ./scripts/build_and_publish_docker.sh
  #   on:
  #     tags: true
  #     condition: $TOXENV = flake8
